# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tamara/2_cours/OOP/lab_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tamara/2_cours/OOP/lab_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tamara/2_cours/OOP/lab_2/CMakeFiles /home/tamara/2_cours/OOP/lab_2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tamara/2_cours/OOP/lab_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_Eleven

# Build rule for target.
test_Eleven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Eleven
.PHONY : test_Eleven

# fast build rule for target.
test_Eleven/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/build
.PHONY : test_Eleven/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named start_test

# Build rule for target.
start_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_test
.PHONY : start_test

# fast build rule for target.
start_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_test.dir/build.make CMakeFiles/start_test.dir/build
.PHONY : start_test/fast

#=============================================================================
# Target rules for targets named start_main

# Build rule for target.
start_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_main
.PHONY : start_main

# fast build rule for target.
start_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_main.dir/build.make CMakeFiles/start_main.dir/build
.PHONY : start_main/fast

Eleven.o: Eleven.cpp.o
.PHONY : Eleven.o

# target to build an object file
Eleven.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/Eleven.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Eleven.cpp.o
.PHONY : Eleven.cpp.o

Eleven.i: Eleven.cpp.i
.PHONY : Eleven.i

# target to preprocess a source file
Eleven.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/Eleven.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Eleven.cpp.i
.PHONY : Eleven.cpp.i

Eleven.s: Eleven.cpp.s
.PHONY : Eleven.s

# target to generate assembly for a file
Eleven.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/Eleven.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Eleven.cpp.s
.PHONY : Eleven.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

test_Eleven.o: test_Eleven.cpp.o
.PHONY : test_Eleven.o

# target to build an object file
test_Eleven.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/test_Eleven.cpp.o
.PHONY : test_Eleven.cpp.o

test_Eleven.i: test_Eleven.cpp.i
.PHONY : test_Eleven.i

# target to preprocess a source file
test_Eleven.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/test_Eleven.cpp.i
.PHONY : test_Eleven.cpp.i

test_Eleven.s: test_Eleven.cpp.s
.PHONY : test_Eleven.s

# target to generate assembly for a file
test_Eleven.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Eleven.dir/build.make CMakeFiles/test_Eleven.dir/test_Eleven.cpp.s
.PHONY : test_Eleven.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... start_main"
	@echo "... start_test"
	@echo "... main"
	@echo "... test_Eleven"
	@echo "... Eleven.o"
	@echo "... Eleven.i"
	@echo "... Eleven.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_Eleven.o"
	@echo "... test_Eleven.i"
	@echo "... test_Eleven.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

