# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tamara/2_cours/OOP/lab_4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tamara/2_cours/OOP/lab_4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tamara/2_cours/OOP/lab_4/CMakeFiles /home/tamara/2_cours/OOP/lab_4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tamara/2_cours/OOP/lab_4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_point

# Build rule for target.
test_point: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_point
.PHONY : test_point

# fast build rule for target.
test_point/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_point.dir/build.make CMakeFiles/test_point.dir/build
.PHONY : test_point/fast

#=============================================================================
# Target rules for targets named point

# Build rule for target.
point: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 point
.PHONY : point

# fast build rule for target.
point/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point.dir/build.make CMakeFiles/point.dir/build
.PHONY : point/fast

#=============================================================================
# Target rules for targets named square

# Build rule for target.
square: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 square
.PHONY : square

# fast build rule for target.
square/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/build
.PHONY : square/fast

#=============================================================================
# Target rules for targets named rectangle

# Build rule for target.
rectangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rectangle
.PHONY : rectangle

# fast build rule for target.
rectangle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/build
.PHONY : rectangle/fast

#=============================================================================
# Target rules for targets named start_rectangle

# Build rule for target.
start_rectangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_rectangle
.PHONY : start_rectangle

# fast build rule for target.
start_rectangle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_rectangle.dir/build.make CMakeFiles/start_rectangle.dir/build
.PHONY : start_rectangle/fast

#=============================================================================
# Target rules for targets named start_square

# Build rule for target.
start_square: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_square
.PHONY : start_square

# fast build rule for target.
start_square/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_square.dir/build.make CMakeFiles/start_square.dir/build
.PHONY : start_square/fast

#=============================================================================
# Target rules for targets named start_point

# Build rule for target.
start_point: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_point
.PHONY : start_point

# fast build rule for target.
start_point/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_point.dir/build.make CMakeFiles/start_point.dir/build
.PHONY : start_point/fast

#=============================================================================
# Target rules for targets named start_test_point

# Build rule for target.
start_test_point: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_test_point
.PHONY : start_test_point

# fast build rule for target.
start_test_point/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_test_point.dir/build.make CMakeFiles/start_test_point.dir/build
.PHONY : start_test_point/fast

point.o: point.cpp.o
.PHONY : point.o

# target to build an object file
point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point.dir/build.make CMakeFiles/point.dir/point.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/point.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/point.cpp.o
.PHONY : point.cpp.o

point.i: point.cpp.i
.PHONY : point.i

# target to preprocess a source file
point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point.dir/build.make CMakeFiles/point.dir/point.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/point.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/point.cpp.i
.PHONY : point.cpp.i

point.s: point.cpp.s
.PHONY : point.s

# target to generate assembly for a file
point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/point.dir/build.make CMakeFiles/point.dir/point.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/point.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/point.cpp.s
.PHONY : point.cpp.s

rectangle.o: rectangle.cpp.o
.PHONY : rectangle.o

# target to build an object file
rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/rectangle.cpp.o
.PHONY : rectangle.cpp.o

rectangle.i: rectangle.cpp.i
.PHONY : rectangle.i

# target to preprocess a source file
rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/rectangle.cpp.i
.PHONY : rectangle.cpp.i

rectangle.s: rectangle.cpp.s
.PHONY : rectangle.s

# target to generate assembly for a file
rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rectangle.dir/build.make CMakeFiles/rectangle.dir/rectangle.cpp.s
.PHONY : rectangle.cpp.s

square.o: square.cpp.o
.PHONY : square.o

# target to build an object file
square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/square.cpp.o
.PHONY : square.cpp.o

square.i: square.cpp.i
.PHONY : square.i

# target to preprocess a source file
square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/square.cpp.i
.PHONY : square.cpp.i

square.s: square.cpp.s
.PHONY : square.s

# target to generate assembly for a file
square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/square.dir/build.make CMakeFiles/square.dir/square.cpp.s
.PHONY : square.cpp.s

test_point.o: test_point.cpp.o
.PHONY : test_point.o

# target to build an object file
test_point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_point.dir/build.make CMakeFiles/test_point.dir/test_point.cpp.o
.PHONY : test_point.cpp.o

test_point.i: test_point.cpp.i
.PHONY : test_point.i

# target to preprocess a source file
test_point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_point.dir/build.make CMakeFiles/test_point.dir/test_point.cpp.i
.PHONY : test_point.cpp.i

test_point.s: test_point.cpp.s
.PHONY : test_point.s

# target to generate assembly for a file
test_point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_point.dir/build.make CMakeFiles/test_point.dir/test_point.cpp.s
.PHONY : test_point.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... start_point"
	@echo "... start_rectangle"
	@echo "... start_square"
	@echo "... start_test_point"
	@echo "... point"
	@echo "... rectangle"
	@echo "... square"
	@echo "... test_point"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
	@echo "... rectangle.o"
	@echo "... rectangle.i"
	@echo "... rectangle.s"
	@echo "... square.o"
	@echo "... square.i"
	@echo "... square.s"
	@echo "... test_point.o"
	@echo "... test_point.i"
	@echo "... test_point.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

